"use strict";
exports.__esModule = true;
var fan_1 = require("./fan");
var SLOW = 1;
var MEDIUM = 2;
var FAST = 3;
var fan1 = new fan_1.Fan(FAST, true, 10, 'yellow');
fan1.getColor;
fan1.getRadius;
fan1.getSpeed;
fan1.getStatus;
console.log(fan1);
var fan2 = new fan_1.Fan(1, true, 10, 'yellow');
fan2.setColor('blue');
fan2.getColor();
fan2.setRadius(5);
fan2.getRadius();
fan2.setSpeed(MEDIUM);
fan2.getSpeed();
fan2.setStatus(false);
fan2.getStatus();
console.log(fan2);
